module.exports = [
  "All",
  "Deposit",
  "Deposit Cancelled",
  "Commission transferred",
  "Bet",
  "Cancel bet",
  "Bet rebate",
  "Withdrawal",
  "Withdrawal cancellation",
  "Win",
  "Re-settle deduction, winning recovery",
  "Manual fund addition",
  "Manual fund deduction",
  "Salary addition",
  "Salary deduction",
  "Bonus fund addition",
  "Bonus fund deduction",
  "Deposit bonus",
  "Registration bonus",
  "First deposit bonus",
  "Sign-in bonus",
  "Red envelope",
  "Payment level award",
  "Invitation reward",
  "Roulette reward",
  "SVIP upgrade reward",
  "SVIP cycle reward",
  "Betting rebate",
  "Task reward",
  "Agent Tasks reward",
  "Invitation first deposit reward",
  "Second deposit bonus",
  "Third deposit bonus",
  "Invitation second deposit reward",
  "Invitation third deposit reward",
  "Buy benefit card",
  "Claim daily benefit card reward",
  "Game moved in",
  "Game moved out",
  "Safe deposit",
  "Safe withdrawal",
  "Social media share award",
];
